# Generated by Django 3.0.2 on 2020-02-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('MA', 'Male'), ('FA', 'Female'), ('OT', 'Others')], default=('OT', 'Others'), max_length=253),
        ),
    ]
