# Generated by Django 3.0.2 on 2020-02-14 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('location_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_location_address', models.CharField(max_length=325)),
                ('event_destination_address', models.CharField(max_length=325)),
                ('set_date_and_time', models.DateTimeField(blank=True, null=True, verbose_name='Date_and_time')),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('is_booked', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('event_LGA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_LG', to='location_app.Directions')),
                ('event_type', models.ForeignKey(default='others', on_delete=django.db.models.deletion.CASCADE, to='core.EventType')),
                ('how_many_bus_are_needed', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bus_needed', to='core.BusNumber')),
                ('location_LGA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_app.Directions')),
                ('number_of_sitters', models.ForeignKey(default='22', on_delete=django.db.models.deletion.DO_NOTHING, to='core.BusNumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BookingBus',
            },
        ),
    ]
